name: CI

on:
  workflow_dispatch:
    inputs:
      Benchmark:
        description: 'Benchmark name'
        default: '*'
        required: false

jobs:

  benchmark:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
      fail-fast: false

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x

    - name: Build
      run: dotnet build -c Release

    - name: Run ${{ github.event.inputs.new_package_version }} benchmark
      run: dotnet run -c Release --no-build --filter ${{ github.event.inputs.new_package_version }}
      working-directory: ./src/SharpFish.Benchmark

    - name: 'Upload ${{ matrix.os }} artifacts'
      continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: artifacts-${{ matrix.os }}-${{ github.run_number }}
        path: ./src/SharpFish.Benchmark/BenchmarkDotNet.Artifacts/results/
        if-no-files-found: error
